
```{r}
library(tidyverse)
library(mirt)
R.utils::sourceDirectory("R")
```

```{r}
pars_1_dif <-
    read_csv("data-parameters/kopf2015-8.csv") %>%
    arrange(desc(easy)) %>%
    mutate(
        item = row_number(),
        nuisance_disc = c(0, 0, 0, 0.1, 0.1, 0, 0, 0)
    )

sim_1_dif <- sim_bias(pars = pars_1_dif, n_ref = 50000, n_foc = 50000, mean_foc = -1)

sim <- read_rds("data-documentation/sim.rds")

fit_mod_intuitive(sim$data, sim$groups) %>% 
    mod_intuitive_to_draws_df() %>% 
    draws_df_to_logit_plot()
```

```{r}
all_other <- dif_all_other(sim_1_dif$data, sim_1_dif$groups)

iterative_backward <- dif_iterative_backward(sim_1_dif$data, sim_1_dif$groups, all_other)

all_other

mod_to_draws_df(all_other)

out_3_biased_items$intuitive_mod[[1]] %>%
    mod_intuitive_to_draws_df() %>%
    draws_df_to_logit_plot() +
    geom_point(data = out_3_biased_items$all_other_final_dif[[1]], aes(x = dif, y = item), color = "red", shape = 1) +
    geom_vline(xintercept = filter(out_3_biased_items$all_other_final_dif[[1]], anchor)$dif[1], linetype = "dashed", color = "red") +
    geom_point(data = out_3_biased_items$it_back_final_dif[[1]], aes(x = dif, y = item), color = "blue", shape = 3) +
    geom_vline(xintercept = filter(out_3_biased_items$it_back_final_dif[[1]], anchor)$dif[1], linetype = "dotted", color = "blue")
```
