---
output:
  bookdown::pdf_document2:
    includes:
    keep_tex: yes
    latex_engine: xelatex
    number_sections: yes
    toc: yes
    toc_depth: 5 

fontsize: 11pt
bibliography: paper.bib
link-citations: yes

title: |
    Promise and peril: Agnostic identification methods  
    for detecting differential item functioning
subtitle: |
    Ben Stenhaug, Ben Domingue, and Mike Frank  
    Stanford University
abstract: |
  It is well known that likelihood ratio tests (LRT) are effective at detecting differential item functioning (DIF) in item response models. However, to use an LRT, the model needs to be identified so that differences in group ability can be disentangled from potential DIF. We summarize existing agnostic identification (AI) methods and propose a variety of new methods. We conduct a simulation study — which we believe to be more realistic than most DIF simulation studies in the literature — and find that one of the proposed new AI methods, All-others-as-anchors-one-at-a-time (AOAA-OAT), significantly outperforms current methods. We also offer a new method, the equal means, multiple imputation logit graph (EM-MILG), that presents clearly all information about possible DIF, including sampling variability in item parameters, to the analyst. \clearpage <!-- https://tinyurl.com/ybremelq -->
header-includes: 
- \usepackage{lineno}
- \linenumbers

- \usepackage{amsmath}
- \DeclareMathOperator*{\argmax}{arg\,max} # for gini coefficient
- \DeclareMathOperator*{\argmin}{arg\,min} # for gini coefficient

- \usepackage{float}
- \usepackage[autostyle, english = american]{csquotes}

- \setlength{\parindent}{4em} # all of this for draft, papaja should take care of things
- \setlength{\parskip}{2em}
- \usepackage{setspace}\doublespacing
- \AtBeginEnvironment{tabular}{\singlespacing} # this makes that table single spaced

- \usepackage{natbib} # citations in that table were a hassle. this is still a bit broken. remember can always change tex file.
---

```{r setup, include = FALSE}
# https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html 

knitr::opts_chunk$set(
    fig.align='center',
    echo=FALSE,
    warning=TRUE,
    fig.pos='H',
    fig.retina = 5
)

library(tidyverse)
library(ggtext)
library(here)
library(mirt)
library(cluster)
library(DescTools)
library(knitr)
library(kableExtra)
set.seed(12345)
R.utils::sourceDirectory(here("R"))

theme_set(theme_bw())
```

<!-- the literature basically talks separately about anchor selection and DIF methods. much more literature is on DIF methods and less is on anchor selection. I'm basically writing a paper about anchor selection and just calling it DIF methods because that seems like where the action is. I'm taking fixed at that the likelihood ratio test is the way to go (and perhaps that deserves more detail)? -->

\begin{table}[H]
\caption{Summary of agnostic identification (AI) methods}
\centering
\begin{tabular}{|p{4cm}|p{6cm}|p{4cm}|}
\toprule

Method & Description & Literature \\

\midrule

all-others-as-anchors (AOAA) & Test if each item has DIF by using all of the other items as anchors (not iterative). & Originally proposed by \cite{lord1980} and formalized by \cite{thissen1993detection} \\\hline

all-others-as-anchors-all-significant (AOAA-AS) & The first iteration is AOAA. All items that test positive for DIF are removed from the anchor set. Continue iterating until no new items test positive for DIF. & Proposed by \cite{drasgow1987study} \\\hline

all-others-as-anchors-one-at-a-time (AOAA-OAT) & The first iteration is AOAA. Only the item that shows the most extreme DIF is removed from the anchor set. Continue iterating until no new items test positive for DIF. & To our knowledge, not proposed or used previously \\\hline

equal means clustering (EMC) & Cluster items based on differences in performance across groups and choose one of the clusters to be the anchor cluster. & Proposed by \cite{bechger2015statistical} and refined by \cite{pohl2017cluster} \\\hline

equal means, multiple imputation logit graph (EM-MILG) & Arbitrarily set both group means to 0, which pushes all group performance differences to the item paramaters, measure variability using multiple imputations, and graph the result. Can be used by an analyst to hand select anchor items & Inspired by pedagolical examples \cite{pohl2017cluster} and \cite{talbot2013taking} \\\hline

multiple imputation logit graph (MILG) & Similar to EM-MILG but used to visualize potential DIF once the model is already identified &  \\\hline

maximizing Gini index (MAXGI) & Arbitrarily set both group means to 0 and then choose an anchor point by maximizing the Gini index & Adapted from work by \cite{strobl2018anchor} \\\hline

minimizing the area between curves (MINBC) & Of the infinite number of model that maximizes the likelihood of the data, choose the one with the minimum total area between the two groups' item characteristic curves & Built on and inspired by work by \cite{raju1988area} and more recently, \cite{chalmers2016might} \\

\bottomrule
\end{tabular}
\label{table:allmethods}
\end{table}







\bibliographystyle{apa}
\bibliography{paper.bib}
