
We described a variety of AI methods and their corresponding acronyms. Some of these methods, such as AOAA and EMC, select anchor items, while others, such as MAXGI and MINBC, select an anchor point. Table \ref{table:allmethods} summarizes all of these methods. Figure \ref{fig:allmethodsfig} shows the results for each method on the demonstration data in a MILG.

\begin{table}[H]
\caption{Summary of agnostic identification (AI) methods}
\centering
\begin{tabular}{|p{3cm}|p{4cm}|p{3cm}|p{3cm}|}
\toprule

Method & Description & Literature & Demonstration data \\

\midrule

all-others-as-anchors (AOAA) & Test if each item has DIF by using all of the other items as anchors (not iterative). & Originally proposed by \cite{lord1980} and formalized by \cite{thissen1993detection} & Did not find any anchor items \\\hline

all-others-as-anchors-all-significant (AOAA-AS) & The first iteration is AOAA. All items that test positive for DIF are removed from the anchor set. Continue iterating until no new items test positive for DIF. & Proposed by \cite{drasgow1987study} & Did not find any anchor items \\\hline

all-others-as-anchors-one-at-a-time (AOAA-OAT) & The first iteration is AOAA. Only the item that shows the most extreme DIF is removed from the anchor set. Continue iterating until no new items test positive for DIF. & To our knowledge, not proposed or used previously & Correctly chose the first five items as anchors \\\hline

equal means clustering (EMC) & Cluster items based on differences in performance across groups and choose one of the clusters to be the anchor cluster. & Proposed by \cite{bechger2015statistical} and refined by \cite{pohl2017cluster} & Worked perfectly by finding two clusters of items, one corresponding to the anchor items and the other corresponding to the items with DIF \\\hline

maximizing Gini index (MAXGI) & Arbitrarily set both group means to 0 and then choose an anchor point by maximizing the Gini index & Adapted from work by \cite{strobl2018anchor} & Set $\mu^{\star\text{foc}} = -0.99$, which is quite close to the data generating value of -1 \\\hline

minimizing the area between curves (MINBC) & Of the infinite number of model that maximizes the likelihood of the data, choose the one with the minimum total area between the two groups' item characteristic curves & Built on and inspired by work by \cite{raju1988area} and more recently, \cite{chalmers2016might} & Set $\mu^{\star\text{foc}} = -1$, which is exactly the data generating value\\

\bottomrule
\end{tabular}
\label{table:allmethods}
\end{table}

```{r allmethodsfig, fig.cap = 'MILG for each of the AI methods applied to the demonstration data. AOAA-OAT and EMC are identified by anchor items (represented by points). MAXGI and MINBC are identified by setting $\\mu^{\\text{foc}}$ set to the anchor point $\\mu^{\\star\\text{foc}}$. AOAA and AOAA-AS are not included as they did not find an identifying assumption.', out.width="70%"}
longify <- function(df, the_method){
    df %>%
        select(-run) %>%
        gather(var, val) %>%
        mutate(var = as_factor(paste0("Item ", parse_number(as.character(var))))) %>%
        filter(val != 0) %>%
        mutate(method = the_method)
}

points <-
    bind_rows(
        out_3_biased_items$AOAA_OAT_final_dif[[1]] %>%
            mutate(
                item = as_factor(paste0("Item ", parse_number(as.character(item)))),
                difference_in_easy = difference_in_easy - difference_in_easy[anchor][1],
                method = "AOAA-OAT"
            ),

        out_3_biased_items$cluster_final_dif[[1]] %>%
            mutate(
                item = as_factor(paste0("Item ", parse_number(as.character(item)))),
                difference_in_easy = difference_in_easy - difference_in_easy[anchor][1],
                method = "EMC"
            ),
    ) %>% 
    select(method, item, anchor) %>% 
    filter(anchor) %>% 
    mutate(val = 0)

data <- out_3_biased_items$sim[[1]]$data
groups <- out_3_biased_items$sim[[1]]$groups

mod_gini <- anchptfocmean_to_final_mod(gini_results$gini_anchor_points, data, groups)
mod_minbc <- anchptfocmean_to_final_mod(min_bc$between_curves_anchor_points, data, groups)

data_for_graph <- 
    bind_rows(
        mod_gini %>% mod_to_draws_df(n = 10000) %>% longify("MAXGI"),
        mod_minbc %>% mod_to_draws_df(n = 10000) %>% longify("MINBC"),
        out_3_biased_items$AOAA_OAT_mod[[1]] %>% mod_to_draws_df(n = 10000) %>% longify("AOAA-OAT"),
        out_3_biased_items$cluster_mod[[1]] %>% mod_to_draws_df(n = 10000) %>% longify("EMC")
    )

data_for_graph %>%
    ggplot(aes(x = val, y = var)) +
    ggridges::geom_density_ridges() +
    geom_point(
        data = points,
        aes(x = val, y = item)
    ) +
    facet_wrap(~ method) +
    labs(
        x = latex2exp::TeX("$\\hat{d_j} = \\hat{b_j}^{ref} - \\hat{b_j}^{foc}$"),
        y = ""
    )
```
