---
output:
  bookdown::pdf_document2:
    includes:
    keep_tex: yes
    latex_engine: xelatex
    number_sections: yes
    toc: yes
    toc_depth: 2
header-includes: 
- \usepackage{float}
- \usepackage[autostyle, english = american]{csquotes}
- \setlength{\parindent}{4em}
- \setlength{\parskip}{2em}
- \usepackage{setspace}\doublespacing
- \usepackage{amsmath}
- \DeclareMathOperator*{\argmax}{arg\,max}
- \AtBeginEnvironment{tabular}{\singlespacing}
- \usepackage{natbib}
fontsize: 11pt
link-citations: yes
title: "Measurement invariance"
subtitle: |
    Ben Stenhaug & Ben Domingue  
    Stanford University
abstract: |
  ABSTRACT TO DO
  <!-- https://tinyurl.com/ybremelq -->
bibliography: paper.bib
---

```{r setup, include = FALSE}
# 
# https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html 

knitr::opts_chunk$set(
    fig.align='center',
    echo=FALSE,
    warning=TRUE,
    fig.pos='H',
    fig.retina = 5
)

library(tidyverse)
library(ggtext)
library(here)
library(mirt)
library(cluster)
library(DescTools)
library(knitr)
library(kableExtra)
set.seed(123)
R.utils::sourceDirectory(here("R"))

theme_set(theme_bw())
```

@lord1980

@drasgow1987study

\begin{center}
 \begin{tabular}{|p{2.5cm}|p{6cm}|p{4cm}|} 
 \toprule
 Method & Description &  Literature \\
 \midrule
 AOAA & Test if each item has DIF by using all of the other items as anchors. Not iterative. & Originally proposed by \cite{lord1980} and formalized by \cite{thissen1993detection} \\ 
 \hline
 AOAA-AS & The first iteration is AOAA. All items that test positive for DIF are removed from the anchor set. Continue iterating until no new items test positive for DIF. & Proposed by \cite{drasgow1987study} \\
 \hline
 AOAA-OAT & The first iteration is AOAA. However, only the item that shows the most extreme DIF is removed from the anchor set. Continue iterating until no new items test positive for DIF. & To our knowledge, not proposed or used previously. \\
 \bottomrule
 \end{tabular}
\end{center}

\bibliographystyle{apa}
\bibliography{paper.bib}
